/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Connect with us',
      items: [
        {
          type: 'link',
          label: 'GitHub',
          href: 'https://github.com/BUTANE-Smart-Chain',
        },
        {
          type: 'link',
          label: 'Twitter',
          href: 'https://twitter.com/Butane_Network',
        },
        {
          type: 'link',
          label: 'Telegram',
          href: 'https://t.me/butanechain',
        },
        {
          type: 'link',
          label: 'Discord',
          href: 'https://discord.gg/zk4t92b9MX',
        },
        {
          type: 'link',
          label: 'Discord Developer',
          href: 'https://discord.gg/je3pBf2h',
        },
        {
          type: 'link',
          label: 'Medium',
          href: 'https://medium.com/@butanegas101',
        },
        {
          type: 'link',
          label: 'Reddit',
          href: 'https://www.reddit.com/r/ButaneNetwork/',
        },
        {
          type: 'link',
          label: 'Youtube',
          href: 'https://www.youtube.com/@ButaneAcademy',
        },
      
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [
        {
          type: 'link',
          label: 'Website',
          href: 'https://butane.tech/',
        },
        {
          type: 'link',
          label: 'DAO',
          href: 'https://commonwealth.im/butane',
        },
        {
          type: 'link',
          label: 'Swap',
          href: 'https://flamez.io/',
        },
        {
          type: 'link',
          label: 'Launch Pad',
          href: 'https://gaspad.io/',
        },
        {
          type: 'link',
          label: 'NFT Marketplace',
          href: 'https://fireflys.art/',
        },
        {
          type: 'link',
          label: 'AirDrop',
          href: 'https://airdrop.butane.tech/',
        },
        {
          type: 'link',
          label: 'Refferal Tool Kit',
          href: 'https://drive.google.com/drive/folders/1L8l-zSaP9OdZJp3S4tcjkHM4DtkwKMqT?usp=share_link',
        },
      
      ],
    },
  ],
};

module.exports = sidebars;